tap "romkatv/powerlevel10k"

brew 'jq'
brew 'mtr'
brew 'nmap'
brew 'ssh-copy-id'
brew 'prettyping'
brew 'rbenv'
brew 'direnv'
brew 'exa'
brew 'romkatv/powerlevel10k/powerlevel10k'

cask 'fig'
cask 'raycast'
cask 'firefox'
cask 'brave-browser'
cask 'forecast'
cask 'onedrive'
cask 'microsoft-teams'
cask 'asana'
cask 'notion'
cask 'hey'
cask 'whatsapp'
cask 'discord'
cask 'microsoft-outlook'
cask 'microsoft-word'
cask 'microsoft-excel'
cask 'visual-studio-code'
cask 'ecamm-live'

mas '1Password for Safari', id: 1569813296
